authors:
- oabo <e99791182@163.com>
dependencies: {}
description: Install docker for Ubuntu
license:
- GPL-2.0-or-later
license_file: ''
name: installdocker
namespace: oabo
readme: README.md
repository: https://github.com/oabo/galaxy/tree/installdocker
tags: []
version: 1.0.9
